AWSTemplateFormatVersion: '2010-09-09'
Description: Master stack to deploy infrastructure for ePlaneAI Website Cron Service

Parameters:
  ProjectName:
    Type: String
    Default: eplane-ai-app-cron-server
    Description: Name of the project (used in naming resources)
  Environment:
    Type: String
    AllowedValues: [dev, prod]
    Description: Deployment environment
  ImageTag:
    Type: String
    Description: Docker image tag (from GitHub SHA)
  AlarmEmails:
    Type: CommaDelimitedList
    Default: ""
    Description: Optional comma-separated list of emails for CloudWatch alarms

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/eplane-ai/${Environment}/${ProjectName}/cloudformation/networking.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/eplane-ai/${Environment}/${ProjectName}/cloudformation/ecs.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        ImageTag: !Ref ImageTag
        DesiredCount: 1
        MinCapacity: 1
        MaxCapacity: 1        
        Cpu: "512"
        Memory: "1024"
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id

  # CloudWatchStack:
  #   Type: AWS::CloudFormation::Stack
  #   DeletionPolicy: Delete
  #   UpdateReplacePolicy: Delete
  #   Properties:
  #     TemplateURL: !Sub "https://s3.amazonaws.com/eplane-ai/${Environment}/${ProjectName}/cloudformation/cloudwatch-dashboard.yaml"
  #     Parameters:
  #       ProjectName: !Ref ProjectName
  #       Environment: !Ref Environment
  #       FullLogGroupName: !GetAtt ECSStack.Outputs.LogGroupName

  # CloudWatchAlarmsStack:
  #   Type: AWS::CloudFormation::Stack
  #   DeletionPolicy: Delete
  #   UpdateReplacePolicy: Delete
  #   DependsOn: ECSStack
  #   Properties:
  #     TemplateURL: !Sub "https://s3.amazonaws.com/eplane-ai/${Environment}/${ProjectName}/cloudformation/cloudwatch-alarms.yaml"
  #     Parameters:
  #       ProjectName: !Ref ProjectName
  #       Environment: !Ref Environment
  #       AlarmEmails: !Ref AlarmEmails

Outputs:
  VPCId:
    Description: VPC ID (forwarded from VPCStack)
    Value: !GetAtt VPCStack.Outputs.VPCId

  ECSClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSStack.Outputs.ECSClusterName

  TaskDefinitionArn:
    Description: Task Definition ARN
    Value: !GetAtt ECSStack.Outputs.TaskDefinitionArn

  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !GetAtt ECSStack.Outputs.LogGroupName

  # AlarmTopicArn:
  #   Description: SNS Alarm Topic ARN
  #   Value: !GetAtt CloudWatchAlarmsStack.Outputs.AlarmTopicArn